sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database event_sourcery_test;' -U postgres
addons:
  postgresql: 9.4
